# Generated by Django 3.1.7 on 2021-03-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210306_0510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
    ]
