# Generated by Django 3.1.7 on 2021-03-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210306_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to='accounts.Student'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to='accounts.Teacher'),
        ),
    ]
